#!/usr/bin/env python3

"""Export a decoder-only workload without making Python a runtime dependency.

The archive deliberately stores host values as float32.  The DTYPE manifest
field describes the storage format the Metal runtime should use; the runtime
performs the final fp16/bf16 conversion when it creates GPU buffers.  This
keeps the archive portable while still allowing references to be generated by
the same low-precision model configuration.
"""

import argparse
import array
import copy
import importlib.util
import json
import math
import re
from types import SimpleNamespace
from pathlib import Path

import torch


class ExportError(RuntimeError):
    pass


DEFAULT_CONFIG = {
    "batch": 1,
    "hidden_size": 64,
    "heads": 4,
    "layers": 2,
    "intermediate_size": 128,
    "vocabulary_size": 128,
    "capacity": 32,
    "prefill_length": 8,
    "decode_count": 8,
    "epsilon": 1e-5,
}


def _load_workload(project_root):
    path = project_root / "workloads" / "pytorch" / "decoder_llm.py"
    spec = importlib.util.spec_from_file_location("tmc_decoder_llm", path)
    if spec is None or spec.loader is None:
        raise ExportError(f"Unable to load decoder workload: {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _values(tensor):
    return tensor.detach().cpu().contiguous().to(torch.float32).reshape(-1).tolist()


def _quoted(value):
    return json.dumps(value, ensure_ascii=False)


def _dtype_token(dtype):
    return {"fp32": "F32", "fp16": "F16", "bf16": "BF16"}[dtype]


def _torch_dtype(dtype):
    # run.sh supplies the device-selected effective precision for references.
    return {
        "fp32": torch.float32,
        "fp16": torch.float16,
        "bf16": torch.bfloat16,
    }[dtype]


def _collect_reference(tensors, prefix, token_ids, logits, next_tokens, caches):
    tensors[f"{prefix}.tokens"] = token_ids
    tensors[f"{prefix}.logits"] = logits
    tensors[f"{prefix}.next_tokens"] = next_tokens
    for layer_index, (key_cache, value_cache) in enumerate(caches):
        tensors[f"{prefix}.layer{layer_index}.key_cache"] = key_cache
        tensors[f"{prefix}.layer{layer_index}.value_cache"] = value_cache


def _normalise_checkpoint_key(key):
    # Checkpoints produced by DataParallel or a thin wrapper commonly carry
    # one or more of these prefixes.  The workload itself keeps the canonical
    # names used by DecoderOnlyLLM.
    prefixes = ("module.", "model.", "decoder.", "transformer.", "backbone.")
    changed = True
    while changed:
        changed = False
        for prefix in prefixes:
            if key.startswith(prefix):
                key = key[len(prefix) :]
                changed = True
                break
    direct = {
        "embed_tokens.weight": "embedding.weight",
        "norm.weight": "final_norm.weight",
        "output.weight": "lm_head.weight",
    }
    if key in direct:
        return direct[key]
    layer_match = re.match(r"^layers\.(\d+)\.(.+)$", key)
    if layer_match:
        layer, suffix = layer_match.groups()
        replacements = {
            "input_layernorm.weight": "input_norm.weight",
            "post_attention_layernorm.weight": "post_attention_norm.weight",
            "self_attn.q_proj.weight": "attention.q_proj.weight",
            "self_attn.k_proj.weight": "attention.k_proj.weight",
            "self_attn.v_proj.weight": "attention.v_proj.weight",
            "self_attn.o_proj.weight": "attention.o_proj.weight",
            "mlp.gate_proj.weight": "mlp.gate_proj.weight",
            "mlp.up_proj.weight": "mlp.up_proj.weight",
            "mlp.down_proj.weight": "mlp.down_proj.weight",
        }
        suffix = replacements.get(suffix, suffix)
        return f"layers.{layer}.{suffix}"
    return key


def _load_tensor_file(path):
    if path.suffix == ".safetensors":
        try:
            from safetensors.torch import load_file
        except ImportError as error:
            raise ExportError(
                "Loading .safetensors requires the local safetensors package."
            ) from error
        return load_file(str(path), device="cpu")
    try:
        try:
            return torch.load(path, map_location="cpu", weights_only=False)
        except TypeError:
            return torch.load(path, map_location="cpu")
    except Exception as error:
        raise ExportError(f"Unable to load checkpoint {path}: {error}") from error


def _checkpoint_files(path):
    if path.is_file():
        return [path]
    for index_name in (
        "model.safetensors.index.json",
        "pytorch_model.bin.index.json",
    ):
        index_path = path / index_name
        if index_path.is_file():
            try:
                index = json.loads(index_path.read_text(encoding="utf-8"))
                names = sorted(set(index["weight_map"].values()))
            except (KeyError, TypeError, json.JSONDecodeError) as error:
                raise ExportError(f"Invalid checkpoint index: {index_path}") from error
            files = [path / name for name in names]
            missing = [str(file) for file in files if not file.is_file()]
            if missing:
                raise ExportError(f"Checkpoint shards are missing: {missing}")
            return files
    for name in ("model.safetensors", "pytorch_model.bin", "model.pt", "model.pth"):
        candidate = path / name
        if candidate.is_file():
            return [candidate]
    raise ExportError(f"No supported checkpoint file found in: {path}")


def _checkpoint_config(path):
    directory = path if path.is_dir() else path.parent
    config_path = directory / "config.json"
    if not config_path.is_file():
        return None
    try:
        values = json.loads(config_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise ExportError(f"Invalid checkpoint config: {config_path}") from error
    return SimpleNamespace(**values)


def _load_checkpoint(path):
    if path is None:
        return {}, None
    path = Path(path).expanduser().resolve()
    if not path.exists():
        raise ExportError(f"Checkpoint does not exist: {path}")
    module = None
    state = {}
    for file in _checkpoint_files(path):
        checkpoint = _load_tensor_file(file)
        if isinstance(checkpoint, torch.nn.Module):
            if module is not None or state:
                raise ExportError("A module checkpoint cannot be combined with shards.")
            module = checkpoint
            shard = checkpoint.state_dict()
        else:
            shard = checkpoint
            if isinstance(shard, dict):
                for key in ("state_dict", "model_state_dict", "model", "weights"):
                    if isinstance(shard.get(key), dict):
                        shard = shard[key]
                        break
        if not isinstance(shard, dict) or not shard:
            raise ExportError(
                "Checkpoint must contain a non-empty state_dict (or a torch.nn.Module)."
            )
        state.update(shard)

    metadata = module if module is not None else _checkpoint_config(path)
    hf_attention = any("self_attn.q_proj.weight" in key for key in state
                       if isinstance(key, str))
    if hf_attention:
        config = getattr(metadata, "config", metadata)
        if config is None or getattr(config, "model_type", None) != "llama":
            raise ExportError("self_attn checkpoints require a supported Llama config.json.")
        heads = getattr(config, "num_attention_heads", 0)
        hidden = getattr(config, "hidden_size", 0)
        if not heads or not hidden or hidden % heads:
            raise ExportError("Invalid Llama hidden size or attention head count.")
        if getattr(config, "num_key_value_heads", heads) != heads:
            raise ExportError("Grouped-query attention checkpoints are not supported yet.")
        if getattr(config, "rope_scaling", None):
            raise ExportError("Scaled RoPE checkpoints are not supported yet.")
        if getattr(config, "hidden_act", "silu") != "silu":
            raise ExportError("The decoder requires SiLU gated MLP activation.")
        if getattr(config, "head_dim", hidden // heads) != hidden // heads:
            raise ExportError("Independent attention head_dim is not supported yet.")
    normalised = {}
    for key, value in state.items():
        if not isinstance(key, str) or not isinstance(value, torch.Tensor):
            continue
        if key.endswith("rotary_emb.inv_freq") or key.endswith("rotary_emb.cos_cached") \
                or key.endswith("rotary_emb.sin_cached"):
            continue
        if not value.is_floating_point():
            raise ExportError(
                f"Checkpoint tensor {key!r} has unsupported dtype {value.dtype}."
            )
        value = value.detach().cpu()
        if hf_attention and ("self_attn.q_proj.weight" in key or
                             "self_attn.k_proj.weight" in key):
            # Convert split-half rotary coordinates to adjacent even/odd
            # coordinates. Applying this permutation to both Q and K preserves
            # their dot product while matching apply_interleaved_rope.
            head_dim = hidden // heads
            if head_dim % 2 or tuple(value.shape) != (hidden, hidden):
                raise ExportError(f"Unsupported rotary projection shape: {key}")
            value = value.reshape(heads, 2, head_dim // 2, hidden)
            value = value.transpose(1, 2).reshape(hidden, hidden).contiguous()
        normalised[_normalise_checkpoint_key(key)] = value
    config = getattr(metadata, "config", metadata)
    if ("lm_head.weight" not in normalised and "embedding.weight" in normalised
            and getattr(config, "tie_word_embeddings", False)):
        normalised["lm_head.weight"] = normalised["embedding.weight"]
    if not normalised:
        raise ExportError("Checkpoint state_dict contains no tensor entries.")
    return normalised, metadata


def _shape(state, name):
    value = state.get(name)
    if value is None:
        return None
    return tuple(int(dimension) for dimension in value.shape)


def _infer_config(state, module):
    inferred = {}
    embedding = _shape(state, "embedding.weight")
    if embedding is not None:
        if len(embedding) != 2:
            raise ExportError("embedding.weight must have shape [vocabulary, hidden].")
        inferred["vocabulary_size"], inferred["hidden_size"] = embedding

    layer_indices = []
    pattern = re.compile(r"^layers\.(\d+)\.")
    for key in state:
        match = pattern.match(key)
        if match:
            layer_indices.append(int(match.group(1)))
    if layer_indices:
        inferred["layers"] = max(layer_indices) + 1

    gate = _shape(state, "layers.0.mlp.gate_proj.weight")
    if gate is not None and len(gate) == 2:
        inferred["intermediate_size"], inferred_hidden = gate
        inferred.setdefault("hidden_size", inferred_hidden)

    rope = _shape(state, "layers.0.attention.rope_cosine")
    if rope is not None and len(rope) == 2:
        inferred["capacity"] = rope[0]

    # A module saved directly may expose the head count and epsilon even when
    # those values are not represented by tensors in the state_dict.
    sources = [module]
    if module is not None:
        sources.append(getattr(module, "config", None))
        layers = getattr(module, "layers", None)
        if isinstance(layers, (torch.nn.ModuleList, list, tuple)) and layers:
            sources.append(getattr(layers[0], "attention", None))
            sources.append(getattr(layers[0], "input_norm", None))
    for source in sources:
        if source is None:
            continue
        for key in (
            "vocabulary_size",
            "hidden_size",
            "heads",
            "layers",
            "intermediate_size",
            "capacity",
            "epsilon",
        ):
            if key in inferred:
                continue
            value = getattr(source, key, None)
            if isinstance(value, (int, float)) and value > 0:
                inferred[key] = value
        if "layers" not in inferred:
            value = getattr(source, "num_layers", None)
            if isinstance(value, int) and value > 0:
                inferred["layers"] = value
        if "heads" not in inferred:
            value = getattr(source, "num_heads", None)
            if isinstance(value, int) and value > 0:
                inferred["heads"] = value
        aliases = {
            "vocabulary_size": "vocab_size",
            "heads": "num_attention_heads",
            "layers": "num_hidden_layers",
            "capacity": "max_position_embeddings",
            "epsilon": "rms_norm_eps",
        }
        for key, alias in aliases.items():
            if key in inferred:
                continue
            value = getattr(source, alias, None)
            if isinstance(value, (int, float)) and value > 0:
                inferred[key] = value
    return inferred


def _resolve_config(arguments, inferred):
    if arguments.checkpoint is not None:
        if getattr(arguments, "heads", None) is None and "heads" not in inferred:
            raise ExportError("Checkpoint head count is missing; provide --heads or config.json.")
        for key in ("hidden_size", "heads", "layers", "intermediate_size", "vocabulary_size"):
            requested = getattr(arguments, key, None)
            if requested is not None and key in inferred and requested != inferred[key]:
                raise ExportError(f"Requested {key}={requested} differs from checkpoint {inferred[key]}.")
    config = {}
    for key, default in DEFAULT_CONFIG.items():
        value = getattr(arguments, key, None)
        if value is None:
            value = inferred.get(key, default)
        config[key] = value
    config["batch"] = int(config["batch"])
    for key in (
        "hidden_size",
        "heads",
        "layers",
        "intermediate_size",
        "vocabulary_size",
        "capacity",
        "prefill_length",
        "decode_count",
    ):
        config[key] = int(config[key])
    config["epsilon"] = float(config["epsilon"])
    if config["batch"] != 1:
        raise ExportError("The decoder archive exporter currently supports batch=1 only.")
    if any(config[key] <= 0 for key in config if key != "decode_count"):
        raise ExportError("Decoder dimensions, capacity, and prefill length must be positive.")
    if config["decode_count"] < 0:
        raise ExportError("decode_count must be non-negative.")
    if config["hidden_size"] % config["heads"] != 0:
        raise ExportError("hidden_size must be divisible by heads.")
    if (config["hidden_size"] // config["heads"]) % 2 != 0:
        raise ExportError("The RoPE head dimension must be even.")
    if config["prefill_length"] > config["capacity"]:
        raise ExportError("prefill_length exceeds cache capacity.")
    if config["prefill_length"] + config["decode_count"] > config["capacity"]:
        raise ExportError("prefill_length + decode_count exceeds cache capacity.")
    if not math.isfinite(config["epsilon"]) or config["epsilon"] <= 0:
        raise ExportError("epsilon must be finite and positive.")
    return config


def _validate_checkpoint_shapes(state, config):
    if not state:
        return
    hidden = config["hidden_size"]
    intermediate = config["intermediate_size"]
    expected = {
        "embedding.weight": (config["vocabulary_size"], hidden),
        "final_norm.weight": (hidden,),
        "lm_head.weight": (config["vocabulary_size"], hidden),
    }
    for layer in range(config["layers"]):
        prefix = f"layers.{layer}"
        expected.update(
            {
                f"{prefix}.input_norm.weight": (hidden,),
                f"{prefix}.attention.q_proj.weight": (hidden, hidden),
                f"{prefix}.attention.k_proj.weight": (hidden, hidden),
                f"{prefix}.attention.v_proj.weight": (hidden, hidden),
                f"{prefix}.attention.o_proj.weight": (hidden, hidden),
                f"{prefix}.post_attention_norm.weight": (hidden,),
                f"{prefix}.mlp.gate_proj.weight": (intermediate, hidden),
                f"{prefix}.mlp.up_proj.weight": (intermediate, hidden),
                f"{prefix}.mlp.down_proj.weight": (hidden, intermediate),
            }
        )
    for name, shape in expected.items():
        tensor = state.get(name)
        if tensor is not None and tuple(tensor.shape) != shape:
            raise ExportError(
                f"Checkpoint tensor {name!r} has shape {tuple(tensor.shape)}; "
                f"expected {shape}. Grouped-query attention is not supported yet."
            )


def _set_storage_precision(model, dtype, metadata=None):
    config = getattr(metadata, "config", metadata)
    theta = getattr(config, "rope_theta", 10000.0)
    if not isinstance(theta, (float, int)) or not math.isfinite(theta) or theta <= 0:
        raise ExportError("rope_theta must be finite and positive.")
    tables = []
    for layer in model.layers:
        attention = layer.attention
        if getattr(config, "model_type", None) == "llama":
            positions = torch.arange(attention.capacity, dtype=torch.float32)
            frequencies = torch.exp(
                torch.arange(0, attention.head_dim, 2, dtype=torch.float32)
                * (-math.log(theta) / attention.head_dim)
            )
            angles = positions[:, None] * frequencies[None, :]
            tables.append((angles.cos(), angles.sin()))
        else:
            tables.append((attention.rope_cosine.float(), attention.rope_sine.float()))
    model.to(dtype=dtype)
    for layer, (cosine, sine) in zip(model.layers, tables):
        layer.attention.rope_cosine = cosine
        layer.attention.rope_sine = sine
    return model.eval()


@torch.no_grad()
def _choose_precision(model, dtype_name, metadata, tokens, decode_count):
    model = _set_storage_precision(model, torch.float32, metadata)
    if dtype_name == "fp32":
        return model, "fp32"
    candidate = _set_storage_precision(copy.deepcopy(model), _torch_dtype(dtype_name), metadata)
    reference_cache = candidate_cache = None
    current = tokens
    maximum_error = 0.0
    for step in range(decode_count + 1):
        expected, reference_cache = model(current, reference_cache)
        actual, candidate_cache = candidate(current, candidate_cache)
        pairs = [(actual, expected)]
        for (ak, av), (ek, ev) in zip(candidate_cache, reference_cache):
            pairs.extend(((ak, ek), (av, ev)))
        for actual_value, expected_value in pairs:
            actual_value = actual_value.float()
            maximum_error = max(maximum_error, (actual_value - expected_value).abs().max().item())
            if not torch.allclose(actual_value, expected_value, atol=2e-2, rtol=2e-2):
                print(f"Precision admission: {dtype_name} -> fp32, step={step}, "
                      f"logits/KV error exceeds atol=0.02, rtol=0.02; max_error={maximum_error:.9g}")
                return model, "fp32"
        next_token = expected[:, -1, :].argmax(dim=-1)
        if not torch.equal(actual[:, -1, :].argmax(dim=-1), next_token):
            print(f"Precision admission: {dtype_name} -> fp32, token mismatch at step={step}")
            return model, "fp32"
        current = next_token.unsqueeze(1)
    print(f"Precision admission: {dtype_name} PASS vs fp32, max_error={maximum_error:.9g}")
    return candidate, dtype_name


@torch.no_grad()
def _make_workload(project_root, arguments):
    module = _load_workload(project_root)
    state, checkpoint_module = _load_checkpoint(arguments.checkpoint)
    inferred = _infer_config(state, checkpoint_module)
    config = _resolve_config(arguments, inferred)
    _validate_checkpoint_shapes(state, config)
    torch.manual_seed(arguments.seed)

    model = module.DecoderOnlyLLM(
        vocabulary_size=config["vocabulary_size"],
        hidden_size=config["hidden_size"],
        heads=config["heads"],
        layers=config["layers"],
        intermediate_size=config["intermediate_size"],
        capacity=config["capacity"],
        epsilon=config["epsilon"],
    ).eval()
    if state:
        try:
            missing, unexpected = model.load_state_dict(state, strict=False)
        except RuntimeError as error:
            raise ExportError(f"Checkpoint parameters are incompatible: {error}") from error
        allowed_missing = {
            name
            for name in missing
            if name.endswith("attention.rope_cosine")
            or name.endswith("attention.rope_sine")
        }
        if set(missing) - allowed_missing or unexpected:
            raise ExportError(
                "Checkpoint keys do not match DecoderOnlyLLM; "
                f"missing={sorted(set(missing) - allowed_missing)}, "
                f"unexpected={sorted(unexpected)}"
            )

    token_ids = torch.randint(
        0, config["vocabulary_size"], (config["batch"], config["prefill_length"])
    )
    model, config["storage_dtype"] = _choose_precision(
        model, arguments.effective_dtype or arguments.dtype, checkpoint_module,
        token_ids, config["decode_count"])

    tensors = {
        "embedding.weight": model.embedding.weight,
        "final_norm.weight": model.final_norm.weight,
        "lm_head.weight": model.lm_head.weight,
        "rope.cosine": model.layers[0].attention.rope_cosine,
        "rope.sine": model.layers[0].attention.rope_sine,
    }
    for layer_index, layer in enumerate(model.layers):
        prefix = f"layer{layer_index}"
        tensors[f"{prefix}.input_norm.weight"] = layer.input_norm.weight
        tensors[f"{prefix}.q.weight"] = layer.attention.q_proj.weight
        tensors[f"{prefix}.k.weight"] = layer.attention.k_proj.weight
        tensors[f"{prefix}.v.weight"] = layer.attention.v_proj.weight
        tensors[f"{prefix}.o.weight"] = layer.attention.o_proj.weight
        tensors[f"{prefix}.post_norm.weight"] = layer.post_attention_norm.weight
        tensors[f"{prefix}.gate.weight"] = layer.mlp.gate_proj.weight
        tensors[f"{prefix}.up.weight"] = layer.mlp.up_proj.weight
        tensors[f"{prefix}.down.weight"] = layer.mlp.down_proj.weight

    logits, caches = model(token_ids)
    next_tokens = logits[:, -1, :].argmax(dim=-1)
    _collect_reference(tensors, "prefill", token_ids, logits, next_tokens, caches)

    current_tokens = next_tokens.unsqueeze(1)
    for step in range(config["decode_count"]):
        logits, caches = model(current_tokens, caches)
        next_tokens = logits[:, -1, :].argmax(dim=-1)
        _collect_reference(
            tensors, f"decode{step}", current_tokens, logits, next_tokens, caches
        )
        current_tokens = next_tokens.unsqueeze(1)

    return config, tensors


def _write_archive(path, config, tensors, requested_dtype, effective_dtype, model_name):
    path = path.resolve()
    path.parent.mkdir(parents=True, exist_ok=True)
    payload_path = path.with_name(path.name + ".bin")
    payload = array.array("f")
    ranges = {}
    for name, tensor in tensors.items():
        offset = len(payload)
        values = _values(tensor)
        payload.extend(values)
        ranges[name] = (offset, len(values))
    with payload_path.open("wb") as output:
        payload.tofile(output)

    lines = [
        "TMC_DECODER_LLM 2",
        f"MODEL {_quoted(model_name)}",
        f"PAYLOAD {_quoted(payload_path.name)}",
        "CONFIG "
        + " ".join(
            str(config[key])
            for key in (
                "batch",
                "hidden_size",
                "heads",
                "intermediate_size",
                "vocabulary_size",
                "layers",
                "capacity",
                "prefill_length",
                "decode_count",
            )
        )
        + f" {config['epsilon']:.9g}",
        f"DTYPE {_dtype_token(requested_dtype)} {_dtype_token(effective_dtype)}",
        f"TENSORS {len(ranges)}",
    ]
    for name, (offset, count) in ranges.items():
        lines.append(f"TENSOR {_quoted(name)} {offset} {count}")
    lines.append("END")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return payload_path


def main():
    parser = argparse.ArgumentParser(
        description="Export a configurable decoder-only LLM and PyTorch references"
    )
    parser.add_argument("--output", type=Path, default=Path("build/decoder_llm.tmc"))
    parser.add_argument("--checkpoint", type=Path, default=None)
    parser.add_argument("--dtype", choices=("fp32", "fp16", "bf16"), default="fp32")
    parser.add_argument("--effective-dtype", choices=("fp32", "fp16", "bf16"), default=None)
    parser.add_argument("--seed", type=int, default=11)
    parser.add_argument("--model-name", default="DecoderOnlyLLM")
    parser.add_argument("--batch", type=int, default=None)
    parser.add_argument("--hidden-size", dest="hidden_size", type=int, default=None)
    parser.add_argument("--heads", type=int, default=None)
    parser.add_argument("--layers", type=int, default=None)
    parser.add_argument("--intermediate-size", dest="intermediate_size", type=int, default=None)
    parser.add_argument("--vocab-size", dest="vocabulary_size", type=int, default=None)
    parser.add_argument("--capacity", type=int, default=None)
    parser.add_argument("--prefill-length", dest="prefill_length", type=int, default=None)
    parser.add_argument("--decode-count", dest="decode_count", type=int, default=None)
    parser.add_argument("--epsilon", type=float, default=None)
    arguments = parser.parse_args()
    project_root = Path(__file__).resolve().parents[1]
    config, tensors = _make_workload(project_root, arguments)
    payload = _write_archive(
        arguments.output, config, tensors, arguments.dtype,
        config["storage_dtype"], arguments.model_name
    )
    print("Decoder-only export: PASS")
    print(f"Manifest: {arguments.output.resolve()}")
    print(f"Payload: {payload}")
    print(
        "Config: "
        f"hidden={config['hidden_size']}, heads={config['heads']}, "
        f"layers={config['layers']}, intermediate={config['intermediate_size']}, "
        f"vocab={config['vocabulary_size']}, capacity={config['capacity']}, "
        f"prefill={config['prefill_length']}, decode={config['decode_count']}, "
        f"requested_dtype={arguments.dtype}, effective_dtype={config['storage_dtype']}"
    )


if __name__ == "__main__":
    try:
        main()
    except ExportError as error:
        raise SystemExit(f"Decoder-only export: FAIL\nExport error: {error}")
